# Site settings
title: "Where there's a will, there's a way" # Your Title
tagline: 'Twisted tales to make you shudder' # A brief tagline for your site
sidebar_image: /images/cover2.jpg

# Build settings
markdown: redcarpet
highlighter: pygments
baseurl: https://englishlearn.github.io # the subpath of your site, e.g. /blog/
